name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install package manager
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build
        working-directory: ./packages/frontend

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages/frontend/dist/spa

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
